# Generated by Django 4.2.5 on 2023-10-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telegram',
            field=models.CharField(blank=True, default='BIO to`ldirilmagan!', max_length=500, null=True),
        ),
    ]
