# Generated by Django 4.2.3 on 2023-08-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_remove_job_is_active_remove_job_is_daily'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary_period',
            field=models.CharField(choices=[('hourly', 'Soatlik'), ('daily', 'Kunlik'), ('weekly', 'Haftalik'), ('monthly', 'Oylik')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
