# Generated by Django 4.2.5 on 2023-09-27 16:28

from django.db import models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_salary_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(max_length=5000)
        ),
    ]
