# Generated by Django 4.2.5 on 2023-11-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(max_length=15),
        ),
    ]
